import { loadImage } from "../lib/NasaImg";
import { loadWeather } from "../lib/Weather";
import { loadQuotes } from "../lib/quotes";
import Head from "next/head";
import Image from "next/image";
import Weather from "../components/weather";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.grid}>
        <div className={styles.weather}>
          <Weather
            city={props.weather.data[0].city_name}
            state={props.weather.data[0].state_code}
            temp={props.weather.data[0].temp}
            desc={props.weather.data[0].weather.description}
          />
        </div>

        <div className={styles.notesContainer}>
          <Image
            width={300}
            height={300}
            className={styles.nasa}
            src={props.data[0].url}
            alt=""
          />
        </div>

        <div className={styles.quote}>
          <p
            className={styles.quoteSz}
            style={{ fontSize: 24, marginBottom: 10 }}
          >
            {props.quote[0].q}
          </p>
          <Link href="/blog/">
            <button>Notes</button>
          </Link>
        </div>

        <div className={styles.backgroundImage}>
          <Image width={300} height={300} src={props.data[1].url} alt="" />
        </div>

        <div className={styles.bottomBackgroundImage}>
          <Image width={300} height={300} src={props.data[2].url} alt="" />
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const data = await loadImage();
  const weather = await loadWeather();
  const quote = await loadQuotes();
  return { props: { data, weather, quote } };
}
