import { loadImage } from "../lib/NasaImg";
import styles from "../styles/Home.module.css";
import Head from "next/head";

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <img className={styles.nasa} src={data[0].hdurl} alt="" />
    </div>
  );
}

export async function getStaticProps() {
  const data = await loadImage();

  return { props: { data } };
}
