import { loadImage } from "../lib/NasaImg";
import Head from "next/head";
import NasaButton from "../components/nasaButton";
import Weather from "../components/weather";
import { loadWeather } from "../lib/Weather";
import Form from "../components/Form";

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Weather
        city={props.weather.data[0].city_name}
        state={props.weather.data[0].state_code}
        temp={props.weather.data[0].temp}
        desc={props.weather.data[0].weather.description}
      />
      <NasaButton imgUrl={props.data[0].hdurl} />
      <Form />
    </div>
  );
}

export async function getStaticProps(context) {
  const data = await loadImage();
  const weather = await loadWeather();

  return { props: { data, weather } };
}
